### ISSUE TITLE
Bug in Reliability Diagram

### ISSUE THREAD

**Issue by cdiazbas** [EFS-OpenSource/calibration-framework#52] opened 2023-12-18 11:08 UTC
The ReliabilityDiagram creates bins with values which are not in the input.
Code to reproduce it: 

```
import numpy as np
import matplotlib.pyplot as plt
from netcal.presentation import ReliabilityDiagram
# Generate true and predicts values
y_true = np.random.randint(0, 2, 100).astype(np.float32)
# Generate perfect predictions:
y_pred = y_true.copy() 
n_bins = 10
diagram = ReliabilityDiagram(n_bins)
_ = diagram.plot(y_pred, y_true)
```

![wrong_output](https://github.com/EFS-OpenSource/calibration-framework/assets/11562491/6d4c2e49-d671-44c2-99ff-b211848c506d)

**Comment by opsavi** [comment] 2024-03-06 12:24
I experienced the same issue. A quick fix is to just comment line 291 and 292 in ReliabilityDiagram.py
https://github.com/EFS-OpenSource/calibration-framework/blob/82e65dc225c7b4443dcd748836ed6b302af12fd2/netcal/presentation/ReliabilityDiagram.py#L291
https://github.com/EFS-OpenSource/calibration-framework/blob/82e65dc225c7b4443dcd748836ed6b302af12fd2/netcal/presentation/ReliabilityDiagram.py#L292

**Comment by fabiankueppers** [comment] 2024-08-08 11:29
Hi @cdiazbas, at the time of development, this was intended behavior since missing bars might be confusing. But I see your point that bars might be misleading which have no underlying data. I will think about it and proabably add either an option to disable this behavior or to mark "empty" bins as such. Thanks for raising attention.

**Comment by fabiankueppers** [comment] 2024-08-08 13:46
Since this is not a bug, I close this issue for now.

**Closed by fabiankueppers** 2024-08-08 13:46 UTC
