### ISSUE TITLE
Seeing strange behavior in reliability diagram for histogram binning

### ISSUE THREAD

**Issue by chris-wells-13** [EFS-OpenSource/calibration-framework#19] opened 2021-08-17 20:41 UTC
I've run HistogramBinning on several datasets and always seem to end up with an empty right-most bin on the post-calibration reliability diagram (see figure below).

![image](https://user-images.githubusercontent.com/73897499/129797377-2a2ab599-b2cf-4305-b1af-7b93c17c3654.png)

**Comment by chris-wells-13** [comment] 2021-08-17 20:47
two notes:
-also shows up in isotonic regression
-goes away if num_bins is the same for the fit and for the reliability diagram

**Comment by fabiankueppers** [comment] 2022-10-18 08:35
@chris-wells-13 are there any updates on this? Could you please share some data where this error occurs? I've recently seen the same behavior at one of our students but did not have access to the data to reproduce.

**Comment by thsno02** [comment] 2023-10-20 09:21
> @chris-wells-13 are there any updates on this? Could you please share some data where this error occurs? I've recently seen the same behavior at one of our students but did not have access to the data to reproduce.

I found same issue. My prediction results didn't contain values that are greater than 0.9, but the histogram still plotted it while scikit-learn not.

**Comment by fabiankueppers** [comment] 2024-08-08 12:54
Closing this issue due to missing information for reproducibility. Please re-open if necessary.

**Closed by fabiankueppers** 2024-08-08 12:54 UTC
